### ISSUE TITLE
What sort of starter content would work well for this design?

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#216] opened 2018-10-20 16:26 UTC
Is this theme going to supply starter content? 
Will it have blocks? Does core support that yet, or is it not necessary for core to do anything different?

One thing it could have is the menu, and the menu could have privacy link.

**Comment by celloexpressions** [comment] 2018-10-23 02:10
Starter content is a relatively new feature in core, dating to WordPress 4.7. As a relatively new feature, and given that bundled themes should be "state of the art," it seems like a mandatory element of Twenty Nineteen. We should also consider the goal of starter content to improve the new user experience with fresh installations of WordPress. Leaving this out of Twenty Nineteen would be a regression relative to the current fresh-install experience with Twenty Seventeen.

This would be a great area for someone with experience building the types of sites that this theme is intended for to contribute.

**Comment by LittleBigThing** [comment] 2018-11-07 17:38
As proposed during one of the Slack chats, I have looked into adding starter content to the theme.

It is explained above why starter content is useful, but I think that for this theme in specific, it could additionally highlight the new block editor's features. It could give a first impression of what can be achieved, but only some basics seem sufficient. And also how this can be achieved using the editor. Once the starter content is saved and a page containing it is edited by the user, (s)he could learn the basics about using the editor. It is certainly an enhancement.

I'll added a PR with a first very rough try for starter content: #510.

Standard, [core provided starter content](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/theme.php?rev=39373#L1910) is not recognised as a block. Starter content needs to contain Gutenberg markup. These are the HTML comments added before and after blocks by Gutenberg, for example `<!-- wp:paragraph -->`, including attributes if present (`<!-- wp:paragraph {"dropCap":true} -->`). Gutenberg will recognise such content as blocks, and they will be nicely editable. To create such starter content, we need to add the blocks we wish to have in the Gutenberg editor, changing to 'code editor' and copying the markup to add it is as starter content. To make it translatable, additional translation functionality (`_x()`) need to be wrapped around text strings.

**What can we add?**
- create a front page using different blocks; for example, columns, a wide-aligned image, a cool blockquote, some color settings, ...
- theme_mods: a page as front page, a blog page ('blog')
- a contact or an about page: core provides these, but they should be updated with some Gutenberg markup to have them opened as blocks and not as a classic block.
- ...

**What do we need for this?**
- design to decide which blocks we use
- content: this can be a bottleneck to, also with regard to translation

Given the timeframe for finishing the theme, it is a big task and not the highest priority. Plus, we should also consider a _fallback for users using the classic editor_. This can be achieved by not adding starter content or adding different starter content based on the existence of the function `register_block_type()`.

**Comment by LittleBigThing** [comment] 2018-11-22 07:07
@kjellr Is adding starter content still on the table with a later RC and a probably postponed 5.0 release?

**Comment by allancole** [comment] 2019-01-10 21:49
I've moved this issue over to Trac here with the patch from #510 :

https://core.trac.wordpress.org/ticket/45927

I'll close this issue for now, and we can continue discussion over in that thread. Thanks!

**Closed by allancole** 2019-01-10 21:49 UTC
Labels: enhancement
