### ISSUE TITLE
Styling blocks without GB

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#503] opened 2018-11-07 04:23 UTC
What should a post with blocks look like if Gutenberg is deactivated?
I'm thinking that it should at least be legible. I think some of the styles are split between the theme and the editor, such as `position: absolute` in one and `position: relative` in the other.
This Firefox screenshot shows the front end post testing cover blocks when GB is deactivated.

![block-cover-no-gb-19](https://user-images.githubusercontent.com/7957680/48110329-2d789a00-e211-11e8-80bd-824f06254e5c.jpg)

This is how it looks in a different theme that has no GB styles.
![block-cover-no-gb-18](https://user-images.githubusercontent.com/7957680/48110523-4cc3f700-e212-11e8-84ad-9cb4c265271d.jpg)

**Comment by joyously** [comment] 2018-11-07 04:29
For reference, this is what it looks like with Gutenberg.
![block-cover-with-gb](https://user-images.githubusercontent.com/7957680/48110751-6f0a4480-e213-11e8-95f9-98e1929477dc.jpg)

**Comment by kjellr** [comment] 2018-11-08 18:59
Thanks, @joyously.

Gutenberg loads some basic front-end styles in order to make certain blocks appear as intended. For instance: making sure galleries appear in columns. This happens by default. 

In addition, themes can opt in to include slightly more opinionated styles from Gutenberg. These are meant to sync up the front and back end display. For instance: adding the horizontal rule to the left of blockquote. This is done via `add_theme_support( 'wp-block-styles' );`, and is used by Twenty Nineteen (as well as many other themes) to establish a great starting point to build off of. 

In 5.0, these styles are called all the time, even when you activate the Classic plugin. So there's no issue there. But on pre-5.0 versions of WordPress, if you deactivate the Gutenberg plugin, neither of these stylesheets exist. That leads to the issues you noted above. In our case, these issues will only happen if you: 

1. Are using WP version pre-5.0
2. Manually install Twenty Nineteen
3. Activate the Gutenberg plugin
4. Create content that uses blocks
5. Then, deactivate the Gutenberg plugin

When this occurs, the behavior in themes will vary: most themes will likely not include fallbacks for every rule in those Gutenberg stylesheets. 

If someone purposefully deactivates Gutenberg this way, I think it's reasonable to expect some loss of functionality. That said, it's not reasonable to have styles break completely. For our purposes, I suggest we take stock of what happens in this circumstance and focus on fixing things that are clearly broken. 

I took a look through my test site, and noted the following errors. 

- Tables lose their border colors. _This is a quick fix. We should take care of it._
- Cover blocks lose their min-height, the positioning styles for their text and the background size/positioning styles for the image. _We should at least add the min-height._
- Left/right aligned Cover blocks lose their `position: relative;` style, so the text inside them is in the wrong spot on the page. They also collapse completely. These are very broken. _We need to sort this out._
- Columns are not arranged in columns anymore: they are stacked. _I think it's fine to keep them this way._
- Galleries are not arranged in columns anymore: they're an unstyled list. _I suggest we add `list-style-type:none;` and leave them this way._
- Dynamic blocks (Latest Posts, etc.) disappear completely. _This is expected and unavoidable._
- Blockquote Size Large citation appears in a larger font size. _We can fix this._
- Pullquote citations appear in a large font size. _We can fix this._
- The citation in solid color Pullquotes is gray instead of white. _We can fix this._
- Headline + text blocks stack vertically and have no padding. _We should at least add padding here._
- Paragraphs with background colors have no additional padding. _This is easy to add._
- File block download buttons lose their white text, making them unreadable. _We should fix this._ 

 I can spin up a PR later to get these started.

**Comment by kjellr** [comment] 2018-11-13 14:44
#521 has been merged, so I'm closing this issue as per my note above:

> If someone purposefully deactivates Gutenberg this way, I think it's reasonable to expect some loss of functionality. That said, it's not reasonable to have styles break completely. For our purposes, I suggest we take stock of what happens in this circumstance and focus on fixing things that are clearly broken.

The blocks won't look exactly as they would when Gutenberg is disabled in this case, but that PR fixed the most egregious errors.

**Closed by kjellr** 2018-11-13 14:44 UTC
Labels: bug, has patch
