### ISSUE TITLE
Left side eccentricity of most of the content, max-width setting for most of the blocks may be wrong?

### ISSUE THREAD

**Issue by igielskv** [WordPress/twentynineteen#662] opened 2018-11-24 08:14 UTC
Hello guys, I just see that most of the Gutenberg blocks in Twenty Nineteen theme aligned by default to the left, at least on laptop (landscape) screen, they do not use full entry-content width. Also most of the blocks when they float to the right, they also align not with entry-content area width but more to the left. This gives the whole page and it's content eccentric feeling to the left.

(Pullquote is one block which I found that doesn't do this, when it is floating to the right, it is aligned with full width of the entry-content area which slightly compensates the eccentricity of whole content.)

I really don't know if this was an intention or if it is a bug. I just feel the blocks should use width of entry-content area to fill the page evenly with equal margins on both sides.

On iPhones or iPads screens in portrait mode this is not an issue and the content blocks are aligned properly with similar margins on both sides.

See the picture attached bellow there's max-width calculation for Paragraph block, as you can see, instead of filling whole entry-content area, it has extra margin on the right. I just don't see any use of this blank space on the Twenty Nineteen theme, correct me if I'm wrong.

May be max-width calculation for the blocks in entry-content area needs revision.

Have great day everyone, bye.
<img width="1436" alt="screenshot 2018-11-24 at 08 46 14" src="https://user-images.githubusercontent.com/7470561/48966032-3fa45780-efc9-11e8-9f09-e06b8374d39c.png">

**Comment by joyously** [comment] 2018-11-24 17:40
That sounds normal for a LTR language. Did you try it with RTL?
Things should not be wide or centered unless the user chooses that.

**Comment by igielskv** [comment] 2018-11-24 23:36
> That sounds normal for a LTR language?

Ok, may be, I was just wondering what is it good for, so much blank space on the right of entry-content? I guess Twenty Nineteen theme doesn't have an intention to introduce dual column layout, (like with aside element right of main entry-content area).

So just to make it clear, it's not bug but expected behavior of Twenty Nineteen theme.
<img width="1436" alt="screenshot 2018-11-25 at 00 21 28" src="https://user-images.githubusercontent.com/7470561/48973881-2394ca80-f04a-11e8-8822-3fccaf9e1683.png">

**Comment by joyously** [comment] 2018-11-25 00:36
I can see this CSS that is questionable
```
.entry .entry-content > *, .entry .entry-summary > * {
    margin: 32px 0;
}
.entry .entry-content > *, .entry .entry-summary > * {
    max-width: calc(6 * (100vw / 12) - 28px);
}
```
Obviously, it is computed for style.css, but it does use only 6 of 12, and does not center it, which is what you are saying looks bad.

**Comment by igielskv** [comment] 2018-11-25 09:47
Yes, that's it, of-course it's quite easy to remove max-width property either from theme CSS or modify this with Additional CSS in Customize and set its value 100% width of its parent.

If Twenty Nineteen's intention was include 2nd column right of main content area, than I understand this, otherwise is probably better to keep left and right margins of the main content same even on wide screens, same like you have them on iPads, iPhones, etc...

**Comment by kjellr** [comment] 2018-11-25 17:53
Thanks for the report, @igielskv. 

>  I really don't know if this was an intention or if it is a bug. I just feel the blocks should use width of entry-content area to fill the page evenly with equal margins on both sides.

The alignment you mention is an intentional design choice. On desktop-width screens, the theme was designed to have "wide" width elements (and non-inline, right-aligned elements) are fully centered within the viewport, whereas the main content column will appear off-centered.

You can see this off-centered approach in the theme's [original design comps](https://make.wordpress.org/core/2018/10/16/introducing-twenty-nineteen/). Here's a version with layout guides visible to help make it more clear: 

![screen-shot-2018-11-25-at-12 46 25-pm](https://user-images.githubusercontent.com/1202812/48982447-a486ad00-f0b0-11e8-8ef0-e097c615d152.gif)

As you noted, to make better use of limited space all content is contained within the center column on screens below `768px`. 

Since  this is behaving as intended, I'm going to close this issue.

**Closed by kjellr** 2018-11-25 17:53 UTC

**Comment by igielskv** [comment] 2018-11-25 20:58
Fair enough, as it is an intentional behavior, it's all clear, thanks for an explanation, will now try to make the best of the information, overall very nicely designed theme, I like it a lot, have great evening everyone.

**Comment by NickFuture** [comment] 2018-12-17 01:32
I'm having an issue with this layout choice... I'm using the PDF Embedder plugin (which says it is compatible with Gutenberg), and when I embed a PDF as a block, it gets cut off. Is there something I'm missing to be able to make the PDF full-width like an image?
