### ISSUE TITLE
Can we use a fallback menu?

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#80] opened 2018-10-16 22:59 UTC
This theme is like Twenty Seventeen in that it is not showing any menu when one is not chosen. 
This is really bad for a new user. The menu function provides a menu fallback by default, so I think it should be used (use core functionality if it exists).

**Comment by 00travelgirl00** [comment] 2018-10-16 23:11
I agree! The expected behavior in my opinion would be, that alle published pages are displayed in order by date of publishing. If I want to change that, I can set up an menu.

**Comment by kjellr** [comment] 2018-10-17 19:04
Thanks for noting that. I believe Twenty Seventeen shows a fallback menu by default, so Twenty Nineteen to do that as well.

**Comment by joyously** [comment] 2018-10-17 19:13
Yeah, you might think it does, but it does not. You actually have to add code to make it not have a fallback, so the fix is easy.

**Comment by allancole** [comment] 2018-10-17 21:19
Hmmm, some good points are mentioned here but how are we sure the “expected behavior” described is actually what our users expect? I know we’ve included an all-pages fallback in some past default themes, but I think taking it out of Twenty Seventeen was the right move, and we shouldn’t go backwards in this theme for a few reasons: 

1) Users who don’t want to show a menu at all will be confused as to how to achieve an empty menu. It’s not intuitive to ask a user to create a new menu and then leave it empty just to show no menu at all. This is similar to why we don’t show “All Widgets” when a user chooses to empty out a widget area.
2) There’s nothing in /wp-admin that suggests where to configure the all-pages fallback. If a new user starts out with a fallback/all-pages menu by default, and they visit the Menus tab where everything is empty, they won’t understand how to change their menu. Or if they discover that they can delete a Page to have it removed from the fallback menu before they discover the Menu tab itself. Then later when they discover how the Menus tab works, they may regret deleting their pages in the first place. 
3) Without the fallback, users are left with an opt-in approach to Menu setup. This encourages them to be intentional about their Menu content. If we add the proposed fallback, we’re telling the theme to decide what their menu should be and then placing the burden on the user to figure out how to override the theme’s defaults. 

Open to hearing other opinions on this ;-)

**Comment by joyously** [comment] 2018-10-17 22:19
The function has a default value of using Pages as the fallback.
I think this is a good opportunity to enhance how the default works. 
There could be a theme option for empty or Pages fallback.
There could be instructional text to guide the user concerning the default.

I don't think it's very useful to have no menu by default, and it's not backwards to have one. A LOT of themes use the core default of a Page menu fallback, so any users switching themes could inadvertently lose their menu.
I was going to say something about the theme previewer, but it looks like they recently added a small menu there. Before, it did not define a menu, and so those themes that don't have a fallback were very difficult to preview (except the first page).

**Comment by kjellr** [comment] 2018-10-18 16:28
_Quoting myself from earlier:_

> Thanks for noting that. I believe Twenty Seventeen shows a fallback menu by default, so Twenty Nineteen to do that as well.

Now that I realize that I was wrong there, I'm going to remove the `task` tag until we reach a decision one way or another.

**Comment by melchoyce** [comment] 2018-10-18 16:32
Not having a fallback menu is a feature, not a bug, IMO. I agree with everything @allancole mentioned, which are the primary reasons we didn't include a fallback menu in Twenty Seventeen.

Will Twenty Eighteen come with demo content? I think having a default menu set up would be a better approach.

**Comment by joyously** [comment] 2018-10-18 16:43
Uh, Nineteen, Mel.
And do you mean starter content? I think it should. But I also think a fallback menu is better since it works with all sites, not just new ones.

**Comment by melchoyce** [comment] 2018-10-18 16:53
Hah, yes, Nineteen! My brain is having trouble skipping a year 😅

**Comment by kjellr** [comment] 2019-01-08 13:30
As per @allancole's [notes above](
https://github.com/WordPress/twentynineteen/issues/80#issuecomment-430793610), Twenty Nineteen shipped without a fallback menu. I'm closing this issue as a result. If this is still a feature you'd like to see considered, please feel free to open a new ticket on Trac: 

https://core.trac.wordpress.org/newticket

**Closed by kjellr** 2019-01-08 13:31 UTC
Labels: needs decision
