### ISSUE TITLE
Bugs with comments

### ISSUE THREAD

**Issue by slaFFik** [WordPress/twentynineteen#706] opened 2018-12-06 21:15 UTC
Bug 1:

![image](https://user-images.githubusercontent.com/282234/49612167-7b1d2980-f9ac-11e8-946d-65a32ec00d3e.png)

Its HTML:
```html
<span class="comment-count">
		<ol class="discussion-avatar-list">
<li><div class="comment-user-avatar comment-author vcard"><img alt="" src="https://secure.gravatar.com/avatar/696ce242e5ecfb9bcecf9d7ec1d19514?s=60&amp;d=mm&amp;r=g" srcset="https://secure.gravatar.com/avatar/696ce242e5ecfb9bcecf9d7ec1d19514?s=120&amp;d=mm&amp;r=g 2x" class="avatar avatar-60 photo" height="60" width="60"></div></li>
</ol><!-- .discussion-avatar-list -->
		<span class="comments-link"><svg class="svg-icon" width="16" height="16" aria-hidden="true" role="img" focusable="false" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M21.99 4c0-1.1-.89-2-1.99-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h14l4 4-.01-18z"></path><path d="M0 0h24v24H0z" fill="none"></path></svg><a href="https://ovirium.com/blog/make-money-buddypress/?customize_changeset_uuid=d33db312-a70f-4cdb-a4bf-c458f9b63d07&amp;customize_autosaved=on&amp;customize_theme=twentynineteen&amp;customize_messenger_channel=preview-3#comments" target="_self">1 Comment<span class="screen-reader-text"> on How to make money with BuddyPress?</span></a></span>	</span>
```
Instead of a counter - latest commenter avatar is displayed and with wrong styles.

---

Bug 2:
![image](https://user-images.githubusercontent.com/282234/49612143-693b8680-f9ac-11e8-8588-053c8deaeb8c.png)

---

WP 5.0, 2019 from the WP.org directory, previewing the theme in a Customizer.

**Comment by allancole** [comment] 2018-12-10 18:52
Interesting. Do you see the same issue happening in the demo?: https://2019.wordpress.net/?p=199

And if so, what browser are you using?

**Comment by laurelfulford** [comment] 2019-01-10 20:49
Thanks for reporting this issue, @slaFFik!

For the first issue (the gravatar being squished), I haven't had any luck recreating this -- I tried viewing a post with a featured image and a single comment in the Customizer, using the following browsers:

* Firefox 64 (OSX 10.14)
* Chrome 71 (OSX 10.14)
* Safari 12 (OSX 10.14)
* Edge 15 & 17 in Windows 10

... but it displays as expected in all cases.

For the second issue, this looks like it's displaying as right (the gravatar and comment count only shows when comments are open), but I might be misunderstanding something!

We are currently working to move Twenty Nineteen fully from this GitHub repo to the WordPress Core Trac -- as we haven't been able to replicate the above, I'm going to close this issue.

However, if you're still seeing this problem, and can provide more information about steps to reproduce, or the browser you're using, that would be greatly appreciated! If so, please open a new Trac ticket here:

http://core.trac.wordpress.org/

Thanks!

**Closed by laurelfulford** 2019-01-10 20:49 UTC
Labels: bug, needs testing
