### ISSUE TITLE
Left aligned image size different in editor and frontend

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/twentynineteen#127] opened 2018-10-17 16:38 UTC
Backend
<img width="1143" alt="bildschirmfoto 2018-10-17 um 18 33 26" src="https://user-images.githubusercontent.com/20684594/47101902-96d14280-d23b-11e8-868a-8c7dfdba7e87.png">

Frontend
<img width="1257" alt="bildschirmfoto 2018-10-17 um 18 33 31" src="https://user-images.githubusercontent.com/20684594/47101903-9769d900-d23b-11e8-9279-d600698009af.png">

**Comment by nielslange** [comment] 2018-10-17 17:06
@fabiankaegy I can see both left and right aligned images working in the back- end the frontend:

<table>
<tr>
<td>Left align:

![screenshot 2018-10-18 at 00 03 51](https://user-images.githubusercontent.com/3323310/47103426-6b654c80-d269-11e8-9d6a-4cf57e627763.png)
</td>
<td>Right align:

![screenshot 2018-10-18 at 00 03 58](https://user-images.githubusercontent.com/3323310/47103424-6accb600-d269-11e8-92de-d23ccac24ce8.png)
</td>
</tr>
</table>


Do you remember which steps to took that lead to this the case?

**Comment by fabiankaegy** [comment] 2018-10-17 17:43
Yes I have cases where it works fine. But especially with large Images (7000px ... ) The editor shows like the screenshot and how I would want it. But even with resizing it it shill shows up like this

**Comment by kjellr** [comment] 2018-10-17 18:44
I was able to reproduce too — but only when using (very) large images. 

I'm wondering if this is actually a Gutenberg bug though — I'm able to reproduce in Twenty Seventeen.

Backend: 

![screen shot 2018-10-17 at 2 39 21 pm](https://user-images.githubusercontent.com/1202812/47108935-f79c5300-d21a-11e8-8ed8-cddb52e54019.png)

Front end (Twenty Nineteen):

![screen shot 2018-10-17 at 2 39 26 pm](https://user-images.githubusercontent.com/1202812/47108948-008d2480-d21b-11e8-8a6d-7dad6524f327.png)

Front end (Twenty Seventeen)

![screen shot 2018-10-17 at 2 42 02 pm](https://user-images.githubusercontent.com/1202812/47108964-0a168c80-d21b-11e8-956a-8bcc4b2ff5ce.png)

Can someone else confirm this behavior in other themes? If so, we'll move this over to the Github repo.

**Comment by joyously** [comment] 2018-10-17 19:03
Did you try it with a theme that has styles in the classic editor?

**Comment by kjellr** [comment] 2018-11-21 14:41
That seems about right, thanks for testing, @designsimply. I'm also unable to reproduce, so I think this got sorted out in Gutenberg at some point. Closing this issue for now. We can re-open later if we see this issue pop up again.

> @kjellr is it best to test with WP 5.0-betas or WP 4.9.8 or is either fine?

From now until release, the code should generally be in sync between the two, so either one (or both) is great. 👍 

Thanks!

**Closed by kjellr** 2018-11-21 14:41 UTC
Labels: bug
