### ISSUE TITLE
Metaboxes are overlapping the Block editor

### ISSUE THREAD

**Issue by andizer** [WordPress/twentynineteen#738] opened 2018-12-14 13:15 UTC
It seems the metabox is overlapping the block editor. Especially bigger metaboxes results in a difficult editing experience:
![edit_post_ _local_wordpress_dev_ _wordpress](https://user-images.githubusercontent.com/325040/50005415-8ffc4d00-ffaa-11e8-9a23-cffc4197accf.png)
In this screenshot I've made a custom post field group and I am using Yoast SEO. 

When I switch back to Twentyseventeen this issue is gone.

This is possibly a regression of #564

**Comment by kjellr** [comment] 2018-12-14 18:01
Thanks for the report, @andizer. What browser, theme, and WP version are you seeing this on? It's working as expected for me using FF 64.0 on MacOS 10.14. Running a fresh install of 5.0:

![yoast](https://user-images.githubusercontent.com/1202812/50019354-5aeafd00-ffa0-11e8-9a3c-f37058036fad.gif)

**Comment by andizer** [comment] 2018-12-17 08:01
I am using Chrome 71.0.3578.98, twentynineteen and WordPress 5.0.1. 

Usually the editor grows when there is more content and the metabox get a position more to the bottom. In this case the metabox keeps overlapping the editor that makes it hard to edit. Only collapsing the metabox will give me more space.

**Comment by kjellr** [comment] 2018-12-17 17:33
Thanks for the additional details. I'm still unable to reproduce. 🤔 

Chrome 71.0.3578.98, MacOS 10.14.2, WP 5.0.1:

![chrome-71](https://user-images.githubusercontent.com/1202812/50104259-8e739480-01f7-11e9-9f97-87f00a551da5.gif)

Tested both with the bundled version of Twenty Nineteen, as well as an uploaded version from this repository. Is it at all possible you're running an old version of Twenty Nineteen? I wonder if someone else can give it a test too. 

Thanks!

**Comment by andizer** [comment] 2019-01-08 12:59
It occurs in version 1.1

**Comment by kjellr** [comment] 2019-01-10 20:56
We're archiving this GitHub repository soon and moving over to Trac now that the theme has been merged into Core. I'm going to close this issue for now, and we can pick up discussion over in this thread:

https://core.trac.wordpress.org/ticket/45926#ticket

Thank you!

**Closed by kjellr** 2019-01-10 20:56 UTC
Labels: bug, needs testing
