### ISSUE TITLE
Add option for Text color and Link Color in Customizer

### ISSUE THREAD

**Issue by monika-12** [WordPress/twentynineteen#339] opened 2018-10-26 06:11 UTC
**Actual:**
When I am using background image then default text color/link color will not work.  There is no option to change link color and text color.

**Expected**
There should be option to add Text Color and Link Color so it will easy for user to change it easily.

**Screenshot**
![image](https://user-images.githubusercontent.com/17018981/47547674-0f0ec680-d914-11e8-973a-1b188290a72c.png)

**Comment by kjellr** [comment] 2018-10-26 12:36
@monika-12  — Just to clarify, are you seeing this with the latest version of the theme, from GitHub? Can you share your browser and OS version so we can try to reproduce?

**Comment by monika-12** [comment] 2018-10-29 05:38
@kjellr 
Yes, I am using the latest master branch from GitHub. 
OS - Windows-10
Browser - Chrome 69

Please see attached screenshot-

![screenshot-wp local-2018 10 29-11-05-00](https://user-images.githubusercontent.com/17018981/47631109-82117a80-db6a-11e8-8f54-b77a8e3928c9.png)

Default Text and Link color are not visible on dark Background Image so there should be option in Customizer to change Text Color and Link Color.

**Comment by kjellr** [comment] 2018-10-29 12:06
Ah, okay — Thanks for clarifying. I don't believe we background images were intended to be allowed in the theme. We might want to remove that option. cc @allancole for confirmation.

**Comment by monika-12** [comment] 2018-10-29 12:17
Oh! That will be great if we removed Background Image option.
@allancole  Please give your confirmation on Background Image option.

**Comment by kjellr** [comment] 2018-10-29 12:57
Actually, I just checked and this option will be removed in #373. I'll keep this open until that is merged just in case though. 👍

**Comment by allancole** [comment] 2018-10-29 23:15
Yup, this was fixed in #373 ;-)

**Closed by allancole** 2018-10-29 23:15 UTC
Labels: bug

**Comment by monika-12** [comment] 2018-10-30 12:14
Great
Thanks!
