### ISSUE TITLE
hovering and clicking submenu arrows

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#586] opened 2018-11-13 21:27 UTC
On a narrow window, the menu arrows are clickable, which causes the submenu to remain open. It seems to affect the previous submenus, however. If you click the 2nd arrow, the first won't show on hover, but the 3rd and 4th will. If you click the 3rd, the two previous won't open, but the next one will.

![prev-menu-2018-11-13 15-16](https://user-images.githubusercontent.com/7957680/48443842-f4cc4980-e757-11e8-8f79-d506f873303a.gif)

If you click to open a long submenu, then hover the ellipsis icon, it overlays the long menu.

![long-menu-overlay-2018-11-13 15-20](https://user-images.githubusercontent.com/7957680/48443845-fa299400-e757-11e8-96da-e8edd744d53e.gif)

**Comment by kjellr** [comment] 2018-11-13 21:32
Thanks @joyously – this seems to be directly related to the issue reported in #561. Both are related to overlap when clicking + hovering, but your example is shown at a smaller breakpoint. Can you confirm that's the case? If so, I'd prefer to migrate this over to the other thread as a comment to keep all related discussion in one thread. 

Thank you!

**Comment by kjellr** [comment] 2018-11-13 21:32
(oops, sorry — didn't mean to close this until you've confirmed that's the case. 🙂)

**Comment by joyously** [comment] 2018-11-13 21:50
It's related, but not the same. This issue is about the fact that only _some_ of the submenus show the hover state when one is clicked.

**Comment by allancole** [comment] 2018-11-14 17:29
Just merged PR #589 which removes the ability to open sub-menus via `click` on the dropdown icon. The hover states still work as expected so accessibility is still maintained. Could you retest this issue against the `master` branch @joyously ?

**Comment by joyously** [comment] 2018-11-14 18:12
Yes, this is fixed for me.
Did this modify touch-keyboard-navigation.js ? When I resized my window to test, I get this error:
```
TypeError: event.target.matches is not a function
http://localhost/review/wp/wp-content/themes/twentynineteen-master/js/touch-keyboard-navigation.js?ver=1.0 line 285
```

**Comment by kjellr** [comment] 2018-11-14 18:23
@joyously I'm seeing that too, in Firefox. I'll open a separate issue for it. 

Thanks!

**Closed by kjellr** 2018-11-14 18:23 UTC
Labels: bug
