### ISSUE TITLE
IE 11: Images not constrained to content area

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentynineteen#264] opened 2018-10-24 14:10 UTC
In IE11, when large images are added to a post/page and an alignment of `alignleft`, `alignright` or `aligncenter` is selected, the images are not constrained by the viewport. See screenshots below

Chrome
![centered-image-chrome](https://user-images.githubusercontent.com/34601694/47435975-940eaa00-d773-11e8-9310-25aa0da2857e.PNG)

IE11
![centered-image-ie11](https://user-images.githubusercontent.com/34601694/47436011-a4268980-d773-11e8-86e4-8cefbfa46888.PNG)

This seems to be caused by styles coming from Gutenberg. 
```
.wp-block-image .aligncenter,
.wp-block-image .alignleft,
.wp-block-image .alignright,
.wp-block-image.is-resized {
    display: table;
}
```

WP Version: 5.1-alpha-20181023.142034
GB Version: 4.2.0-alpha-9c303cc

**Comment by joyously** [comment] 2018-10-24 14:47
The style mentioned above could be the reason that the alignleft and alignright had a display property, which we have removed. I suggest that this `display: table` property is overridden, rather than adding the display property back, because of all the legacy alignleft and alignright styles that would be affected (which is why we removed it).

**Comment by kjellr** [comment] 2018-10-29 02:10
I was able to reproduce this in other themes, so this one should be fixed at the Gutenberg level, not just in our theme. 👍  I filed a bug here to track it: https://github.com/WordPress/gutenberg/issues/11183

Thanks for highlighting the issue!

**Closed by kjellr** 2018-10-29 02:10 UTC
Labels: bug, needs testing
