### ISSUE TITLE
Editor styles strange spacing

### ISSUE THREAD

**Issue by jeroenrotty** [WordPress/twentynineteen#187] opened 2018-10-19 12:58 UTC
Making up a first post while twentynineteen is active, placing a space has like double width until you type a letter. Something is buggy probably in the editor styles.
![image 2018-10-19 at 2 57 21 pm](https://user-images.githubusercontent.com/7323966/47219535-601c3900-d3af-11e8-8318-f8e5b41f3ca7.png)

Too clarify, this is on a local dev with only Gutenberg active, fresh install. Doesn't happen on twentyseventeen.

**Comment by kjellr** [comment] 2018-10-23 12:46
@jeroenrotty — I gave this a try today and was unable to reproduce. 🤔 

![screen shot 2018-10-23 at 8 45 06 am](https://user-images.githubusercontent.com/1202812/47361472-044bfb80-d6a0-11e8-9d5a-f80558d91360.png)

Can you share what browser and operating system you're seeing this with? Thanks!

**Comment by richsalvucci** [comment] 2018-10-23 17:20
I can replicate with Chrome 69 and Mac OS Sierra 10.12.6. I would type a word, hit the space bar and then it would jump back after I resumed typing. I also tested with Fire Fox 62 and the issue was not happening.

**Comment by kjellr** [comment] 2018-10-23 17:50
Ah, I can see it in Chrome 69, too:

![space](https://user-images.githubusercontent.com/1202812/47379933-47bb5f80-d6ca-11e8-9764-168175062e23.gif)

This is an odd one. When you insert a space, the editor adds `&nbsp;` to the end of your line. My guess is that for some reason, that non breaking space is styled too be wider than the rest of the spaces in the sentence. We'll need to do some digging to figure this one out.

**Comment by jeroenrotty** [comment] 2018-10-23 19:01
@kjellr I'm using the latest OSX and latest Chrome (both stable)

**Comment by jasmussen** [comment] 2018-11-02 12:49
Reported this as an upstream issue: https://github.com/WordPress/gutenberg/issues/11405 

I don't think there's a fix in TwentyNineteen, outside of swapping out the font :(

**Comment by kjellr** [comment] 2018-11-09 17:37
Closed via #463

**Closed by kjellr** 2018-11-09 17:37 UTC
Labels: bug, needs testing
