### ISSUE TITLE
Right aligned button blocks are too far to the right

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentynineteen#611] opened 2018-11-16 03:34 UTC
When adding buttons with a right align next to a paragraph block, the expected result is for the text to wrap around the button, just like with the left aligned button.
This happens both with and without links in the button.

Single post view in Chrome version 70.0.3538.102 on pc, win 10:

![button-post-view](https://user-images.githubusercontent.com/7422055/48596132-e187cc80-e957-11e8-8352-1cc4c7599246.png)

Also tested on Firefox version 63.0.3 and Edge with the same result

It aligns correctly in the editor.
![button-editor](https://user-images.githubusercontent.com/7422055/48596065-af766a80-e957-11e8-9f2b-475d01b69459.png)

![button](https://user-images.githubusercontent.com/7422055/48596154-04b27c00-e958-11e8-8c6d-b2229d72caf9.gif)

**Comment by kjellr** [comment] 2018-11-16 13:55
Hi @carolinan — This is behaving as designed. The theme is meant to have right-aligned elements extend beyond the text column on larger screen sizes. This behavior is apparent in the Pullquote block shown in the comps shared in [the announcement post](https://make.wordpress.org/core/2018/10/16/introducing-twenty-nineteen/):

![post-gutenberg-in-device](https://user-images.githubusercontent.com/1202812/48625432-3722a000-e97d-11e8-8bd2-a97e166f7f0f.jpg)

The reason you're seeing differently in your editor GIF is because the sidebar is creating a narrower viewport in the editor view. If you were to hide the sidebar (or make your window larger), you'll see the button extend to the right: 

![alignment](https://user-images.githubusercontent.com/1202812/48625328-e6ab4280-e97c-11e8-8918-a953b66a6bf3.gif)

I'm going to close this now, but we can continue discussing if necessary. Thanks for the report!

**Closed by kjellr** 2018-11-16 13:55 UTC

**Comment by kjellr** [comment] 2018-11-16 18:33
> Since right align is not modified for RTL, does it work correctly in RTL?

Yes, it is reversed in RTL, so those rules apply to the left alignment instead. 

![screen shot 2018-11-16 at 1 32 18 pm](https://user-images.githubusercontent.com/1202812/48640257-28031880-e9a4-11e8-8d2b-eacad4b2c78b.png)
![screen shot 2018-11-16 at 1 32 58 pm](https://user-images.githubusercontent.com/1202812/48640258-28031880-e9a4-11e8-9633-1315dacbeb54.png)
