### ISSUE TITLE
Layout is broken in backend for custom post types

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/twentynineteen#599] opened 2018-11-14 22:46 UTC
Using a custom post type (for example this plugin https://wordpress.org/plugins/very-simple-event-list/ ) is leading to truncated icons at the bottom of the editor:

<img width="767" alt="bildschirmfoto 2018-11-14 um 23 14 57" src="https://user-images.githubusercontent.com/870475/48517596-1f58f800-e867-11e8-97cb-6789a0853c5d.png">

5.0-beta4-43896 with just the mentioned plugin activated.

**Comment by websupporter** [comment] 2018-11-15 06:17
I tested it with the same beta and can confirm. The plugin adds a metabox. If you disable the metabox the view is okay.

TwentyNineteen with metabox:
![grafik](https://user-images.githubusercontent.com/6458412/48533785-8221b200-e8ae-11e8-97b9-398d8e423b07.png)

TwentyNineteen without the metabox:
![grafik](https://user-images.githubusercontent.com/6458412/48533806-91086480-e8ae-11e8-8527-a018b1546194.png)

TwentySeventeen with metabox:
![grafik](https://user-images.githubusercontent.com/6458412/48533845-b09f8d00-e8ae-11e8-9530-e7691a6a949e.png)

Tested with:
Ubuntu 14.04
Firefox Quantum

**Comment by kjellr** [comment] 2018-11-15 15:08
Thanks for the report. I believe this may be a duplicate of https://github.com/WordPress/twentynineteen/issues/564, which was fixed in #565 (and then readdressed in #575 🙂).

Here's what I'm seeing when I manually install the current version of the theme (from Github) using 5.0-beta4-43896:

![event-plugin](https://user-images.githubusercontent.com/1202812/48561107-46daaf80-e8bd-11e8-9958-922fa99e82ad.gif)

Would you mind double checking using the latest version [downloaded from Github](https://cloudup.com/cVi84fPC1u9)? Thank you!

**Comment by Zodiac1978** [comment] 2018-11-16 10:01
Hi @kjellr - with the latest version from Github the issue is fixed. Thanks for the hint. 👍 

But the German translation is longer than the English one and the text is still overlapping:
![bildschirmfoto 2018-11-16 um 10 55 33](https://user-images.githubusercontent.com/870475/48614481-a48afc80-e98e-11e8-9372-b399cac4222e.png)

Should I open a new ticket for this or can we handle this in this ticket?

Feel free to close or rename this ticket to handle this.

**Closed** 2018-11-16 10:03 UTC
Labels: needs testing

**Comment by kjellr** [comment] 2018-11-16 13:31
Thanks @Zodiac1978!
