### ISSUE TITLE
[PROPOSAL] Add Developer Tooling 🎯 

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/twentynineteen#70] opened 2018-10-16 21:49 UTC
TwentyNineteen's design is looking pretty impressive. Also, glad to see that Gutenberg is moving forward. I wanted to start a conversation around build developer tooling for building a theme.

I don't see a `package.json` file in [the repo](https://github.com/WordPress/twentynineteen/) let alone any tooling whatsoever. I did read that Sass might be used which will, of course, need some sort of build tooling.

I have created a [proposal to introduce build tooling](https://github.com/ahmadawais/Proposal-Modern-Tooling) in this default WordPress theme for a number of reasons mentioned in there.

---
<p align="center">
  <br>
  <a href="https://github.com/ahmadawais/proposal-modern-tooling">
    <img src="https://on.ahmda.ws/954684/c" />
  </a>
</p>

<h1 align="center">Proposal: Modern Dev Tooling</h1>

<p align="center">
  A developer build tooling proposal for default and modern JavaScript based WordPress Core.
</p>

<p align="center">
  <a title="Autho — Ahmad Awais" href="https://AhmadAwais.com/">
    <img src="https://img.shields.io/badge/by-AHMAD%20AWAIS-gray.svg?colorA=757575&colorB=EF6C00&style=flat">
  </a>
  <a title="Follow on Twitter" href="https://twitter.com/MrAhmadAwais">
    <img src="https://img.shields.io/twitter/follow/MrAhmadAwais.svg?style=social&label=Follow">
  </a>
  <br>
  <br>
</p>

## GOALS

Hey, folks! 🙌

The goal behind creating this proposal document is to help convince the WordPress community, core developers, and especially the contributors behind the all-new [Twenty-Nineteen](https://github.com/WordPress/twentynineteen/) default WordPress theme to use developer build tooling. Which in turn will help modernize

## CONTEXT

I'm a full-time open source dev with hundreds of [developer-tooling](https://github.com/AhmadAwais) related FOSS (Free & Open Source Software) projects, one of which is most relevant to this proposal — it's called [create-guten-block](https://github.com/ahmadawais/create-guten-block). Investing in better developer experience and dev-tooling for WordPress developers in the post-Gutenberg world is vital.

#### STATS

The [create-guten-block](https://github.com/ahmadawais/create-guten-block) is used by ~200 Gutenberg WordPress plugins on the WordPress.org repo (As per my knowledge, that is 90% of the total plugins using Gutenberg on WP.org). CGB has about ~1500 Stargazers/forks and has been downloaded 100,000+ times.

The reason to share this context and the stats is to make a point that developers need to have better tooling at their disposal for not only a better development experience but also building plugins/themes based on Gutenberg with high-quality code. These stats are a testament towards the need of such tooling.

## BENEFITS

For years, default themes have been the source of truth for many new developers, so it's my recommendation that we start [Twenty-Nineteen](https://github.com/WordPress/twentynineteen/) default WordPress theme with developer build tooling in place. It will be beneficial for the WordPress community in many ways, some of which are listed below:

#### 🗃️ **MODERN CODE**

- Use of modern JavaScript, i.e. ES6+
- WordPress will have a modern code base
- Offline support for WordPress themes will lead to 10x better UX
- It will encourage the use of the latest JavaScript and PHP versions
- The possibility of a modern code base with PWAs, Web/Service Workers
- Make it easier to transition towards a more modular code for WordPress Core

#### 🏇 **FASTER WEB**

- WordPress is 32% of the meaningful web at the moment
- Build tools, i.e. webpack will help make 32% of web faster
- JS tree-shaking, removal of unused CSS, optimized mobile sites — all big wins

#### 🌟 **QUALITY CODE**

- Build tooling can help add ESLint & Prettier to the mix
- ESLint/Prettier + other linters help improve code quality
- Build tools make it easier to use standard coding best practices
- Modern code testing, coverage, deployment, and semantic versioning tools

#### 🦁 **DEVELOPER EXPERIENCE**

- Developer tooling will help improve the DX (Developer Experience)
- Integrations with modern JavaScript eco-system will become easier
- Generally, all build-tools (if used the right way) make developers happy
- Advanced JavaScript developers at Enterprise companies could contribute code

## **SUGGESTIONS**

For the development of [Twenty-Nineteen](https://github.com/WordPress/twentynineteen/) default WordPress theme, I suggest the inclusion/building of following dev-tools:

- `webpack` —  JavaScript bundler
- `Babel` —  Using Modern JavaScript today
- `ESLint` — Code linting and error reporting
- `Prettier` — Code reformatting as per set standards
- `phpcs` - PHP Code Sniffer to uphold WP PHP Code Standards
- `phpcbf` - PHP Code Beautifier and fixer comes with `phpcs` package
- `create-guten-block` — Sane defaults #ZeroConfig Gutenberg starter kit

## **FAQs**

It's expected to have some sort of backlash towards this proposal so, I am going to keep a log of frequently asked questions and their answers.

#### Are you suggesting we build custom blocks inside a WordPress Theme?

**NO**. I never said that. Since the day I built [create-guten-block](https://github.com/ahmadawais/create-guten-block) I have been preaching the same lesson, `Custom blocks should only be built inside plugins`. Yes, blocks go in plugins.

And in this case I am suggesting that we build a TwentyNineteen Companion plugin to showcase how we can extend WordPress with custom blocks. WordPress is a CMS and for building custom blocks we'll need companion plugin with the theme. That plugin should have a build tooling process to it. Default themes used to do that. TwentySeventeen has custom pages and customizer helped. With TwentyNineteen we can showcase custom blocks as well. Developers look at default themes to derive inspiration for their work.

That's what I am recommending.

#### TwentyNineteen should be kept simple!

Sure, it should be. But there's an opportunity here that can be explored. If we built Gutenberg to only build simple CSS only WordPress themes without showcasing what custom blocks are now capable of — then we just wasted two years for nothing.

I get the idea that there should be a simple theme to showcase simple things. But there can easily be a companion plugin to showcase how to extend WordPress with Gutenberg and improve your dev experience with dev tooling.

> _*NOTE*_: I think all of the custom blocks related code should probably go in a companion plugin for this theme. That has always been the general consensus and my recommendation to fellow developers.

## WHAT'S NEXT

> For further discussions I have opened up this issue on the [TwentyNineteen repo →](https://github.com/WordPress/twentynineteen/issues/70)

Peace! ✌️

**Comment by joyously** [comment] 2018-10-16 21:57
I think this is a lot for a theme, especially the guten-block. Themes should not have blocks.
I vote to use the least tooling possible.

**Comment by ahmadawais** [comment] 2018-10-16 22:12
@joyously That's a good suggestion. I forgot to add one suggestion I had in mind that there should be a companion plugin with this theme which should have the tooling in it. I should probably update above.

**Comment by mor10** [comment] 2018-10-17 04:47
Somewhat duplicate of #34

**Comment by mharis** [comment] 2018-10-17 08:36
There is discussion at #30 as well.

**Comment by swissspidy** [comment] 2018-10-17 08:50
I think past default themes have shown that too much tooling only hurts contributors and especially users without technological knowledge who just want to mess with their theme. The hurdles were just too high.

> WordPress is a CMS and for building custom blocks we'll need companion plugin with the theme.

That depends on whether custom blocks are actually planned or not. A default theme should just work out of the box and work with what is there.

If a companion plugin is needed at some point, it can be developed in a separate repository with its own tooling.

**Comment by ihorvorotnov** [comment] 2018-10-17 09:13
While I personally prefer doing everything via code (and tooling in this case is unavoidable), the default theme in my opinion must be as simple as possible. It is a theme that newbies and non-techies start to play with, using the built-in code editor first. This theme is built for them first. Advanced users are capable of setting up the tooling of their choice on their own. However, a companion plugin sounds like an interesting experiment to me.

**Comment by dingo-d** [comment] 2018-10-17 16:39
@nielslange I think that developers at _s are using just node-sass [ref](https://github.com/Automattic/_s/pull/1159/files)

**Comment by mtomas7** [comment] 2018-10-18 15:06
As a non-professional theme developer, I would support this initiative if it would be possible to work only with notepad++ for the folks who do not have the skill/knowledge how to use dev. tools.

That means if Dev-tooling is a nice option for those who can use it and doesn’t impair the ability to play with the theme for beginners.

**Comment by dingo-d** [comment] 2018-10-18 18:00
@mtomas7 Don't be afraid of tooling. They are here to help and advance your knowledge. The point is to have a good documentation if you are using tooling so that you can learn and understand why you are using them 🙂

**Comment by nielslange** [comment] 2018-10-25 14:05
Closed due to the merge of #169.

**Closed by nielslange** 2018-10-25 14:05 UTC
