### ISSUE TITLE
Add widget area(s) to the footer

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#14] opened 2018-10-16 14:29 UTC
The theme currently doesn't include any widget areas. We should add at least one to the page footer.

**Comment by LittleBigThing** [comment] 2018-10-16 16:49
I agree to have it/them in the footer. That is probably the area that can be implement the quickest while profiting from Gutenberg's new features like wide-align and columns.

Maybe interesting to check with leads of Gutenberg's phase 2 which includes "replacing widgets with blocks in registered sidebars"?

**Comment by 00travelgirl00** [comment] 2018-10-16 22:49
@melchoyce Yes, that would be an option. Just in my experience, new WordPress User have a hard time to find out how to do that. Because:

1. Create the pages
2. Create an Menu
3. Find the Widget Areas
4. Find the Menu Widget 
5. Choosing the created Menu

By using the Footer Menu, the users only have to:

1. Create the pages
2. Create an Menu
3. define the position 

it is also easier to have an overview about the menus, because of the second tab in "Apperance" - "Menus"

Are there any points agains an footer menu position?

**Comment by joyously** [comment] 2018-10-17 00:44
I would like to see a normal sidebar. I really don't like web sites with no sidebars. They feel so dead-ended and static.

**Comment by nielslange** [comment] 2018-10-24 09:33
@kjellr It looks like the footer widget area issue would be solved with @fabiankaegy's PR #61, wouldn't it?

**Comment by fabiankaegy** [comment] 2018-10-24 11:49
@nielslange I believe the problem is that I haven’t gotten around to adding styles for the core widgets jet. So if someone wants to take that up they are welcome to do so. At the moment I’m working on getting #113 done.

**Comment by nielslange** [comment] 2018-10-24 12:00
@fabiankaegy Thanks for your reply. I'll take over this issue then. ;)

**Comment by kjellr** [comment] 2018-10-24 13:11
Thanks, @fabiankaegy + @nielslange for your progress on these issues!

**Comment by allancole** [comment] 2018-10-30 01:36
Closing this since the solution got merged in with #61

**Closed by allancole** 2018-10-30 01:36 UTC
Labels: task
