### ISSUE TITLE
Display "posted on" date

### ISSUE THREAD

**Issue by briannaorg** [WordPress/twentynineteen#166] opened 2018-10-18 19:48 UTC
As discussed in [#131](https://github.com/WordPress/twentynineteen/issues/131), the post date is not currently being displayed, though there is a function for it in /inc/template-tags.php.

**Comment by designsimply** [comment] 2018-10-19 00:13
Thank you for the pull request at #168! 

I'm closing this issue as a duplicate of #139 so we can consolidate into one issue.

**Closed by designsimply** 2018-10-19 00:13 UTC
Labels: duplicate
