### ISSUE TITLE
Heading not aligned with the rest of the content

### ISSUE THREAD

**Issue by multiformeingegno** [WordPress/twentynineteen#741] opened 2018-12-15 19:07 UTC
On a stock installation of WP 5.0.1
![titlenotaligned](https://user-images.githubusercontent.com/4039005/50046521-a8e52b00-009c-11e9-9cdf-901764939760.PNG)

**Comment by kjellr** [comment] 2018-12-17 17:52
Hi, @multiformeingegno — Can you provide more details? Which page are you seeing this on?

_MacOS 10.14.2, Chrome 71.0.3578.98. Fresh install of WP 5.0.1_

I tried the empty search results page: 

![screen shot 2018-12-17 at 12 50 08 pm](https://user-images.githubusercontent.com/1202812/50105308-50c43b00-01fa-11e9-87c1-e57b42903e9f.png)

... and the 404 page: 

![screen shot 2018-12-17 at 12 52 05 pm](https://user-images.githubusercontent.com/1202812/50105395-93861300-01fa-11e9-8dd9-750c1cd91db0.png)

But neither one appears to have this issue.

**Comment by multiformeingegno** [comment] 2018-12-17 18:47
Home page with 0 posts

https://tardis.s5lab.space/

**Comment by kjellr** [comment] 2019-01-09 20:30
Thanks @multiformeingegno — I'm able to reproduce when there are no posts. Since we're closing down this GitHub repository soon and transitioning to Trac, I've posted a fix over there:

https://core.trac.wordpress.org/ticket/45887

Since that's up there, I'm going to close this issue for now. Thanks again for the report, and feel free to weigh in there with any other thoughts.

**Closed by kjellr** 2019-01-09 20:30 UTC
Labels: bug, move to trac
