### ISSUE TITLE
featured image also added as background-image in post lists

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentynineteen#232] opened 2018-10-22 13:11 UTC
The featured image is displayed in different ways on singular and on index/archive pages.

On singular pages (post and page), it is displayed as a background image, added by the [`twentynineteen_header_featured_image_css`](https://github.com/WordPress/twentynineteen/blob/1d47dac733db1e373929674e5d3eaefc700e961a/inc/template-tags.php#L162) function via [`functions.php`](https://github.com/WordPress/twentynineteen/blob/1d47dac733db1e373929674e5d3eaefc700e961a/functions.php#L142).

On list pages (index and archive lists), it is displayed as an `<img>` added by the `the_post_thumbnail()` function. An anchor element is wrapped around this image that links to the permalink of the post. This `<a>` element also contains the same featured image as a background image. This background image is removed in the PR below.

**Comment by kjellr** [comment] 2018-10-22 17:44
Duplicate of #234. (Likely related to GitHub's oddities today. 🙂)

**Closed by kjellr** 2018-10-22 17:44 UTC
Labels: duplicate

**Comment by LittleBigThing** [comment] 2018-10-22 20:02
Indeed, I wrote that explanation at least twice... :-)
Thanks!
