### ISSUE TITLE
Default font Noto serif is still loading in the editor

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentynineteen#700] opened 2018-12-02 07:47 UTC
Although the editor is styled to match the frontend of the site, including fonts, the default font Noto serif is still loaded in the editor.

![screenshot 2018-12-02 at 08 33 37](https://user-images.githubusercontent.com/5901923/49337140-ce8b2280-f60e-11e8-9144-a79f9f46cb5b.png)

Can we dequeue it?

Related to #181.

**Comment by kjellr** [comment] 2018-12-03 17:17
I'm not actually sure! It's _probably_ okay to dequeue it, but we should (obviously) test it out.

**Comment by LittleBigThing** [comment] 2018-12-05 11:31
I don't think we can, actually. https://github.com/WordPress/gutenberg/blob/1ee20134ada0415c3affe681e0c68cd19d2668c5/lib/client-assets.php#L398

Anyone?

I opened an [issue](https://github.com/WordPress/gutenberg/issues/12611) for Gutenberg.

But I think we should, unless we would get in trouble for any locale. But I suppose that system fonts are properly equipped for all languages.

**Comment by hunter74** [comment] 2018-12-11 14:13
It´s a big problem (also an GDPR PProblem)  that my frontend (when logged out) is loading that Noto Serif font  ...  wp-editor-font    and all other edotr styles.   
But Cookies needed to be accepted for the Noto font.

**Comment by kjellr** [comment] 2018-12-11 14:19
@hunter74: Can you clarify exactly what you're seeing? I'm not able to reproduce this. Twenty Nineteen does not call for Noto Serif at all, so I don't think this would be related to the theme.

**Comment by hunter74** [comment] 2018-12-11 14:35
> @hunter74: Can you clarify exactly what you're seeing? I'm not able to reproduce this. Twenty Nineteen does not call for Noto Serif at all, so I don't think this would be related to the theme.

i am sorry it was the animate blocks plugin doing that

**Comment by kjellr** [comment] 2019-01-10 15:11
Thanks for the issue, @LittleBigThing. Since I don't believe we can do anything about this until Gutenberg gives us an opportunity to dequeue the font, I'm going to close this issue rather than port it over to Trac. If https://github.com/WordPress/gutenberg/issues/12611 gets resolved, we can add a new ticket to Trac and take care of it then. 

Thank you!

**Closed by kjellr** 2019-01-10 15:11 UTC
Labels: question

**Comment by LittleBigThing** [comment] 2019-01-10 16:56
Ok, thanks!
