### ISSUE TITLE
Navigating submenu open-button adding duplicate class

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentynineteen#716] opened 2018-12-07 15:39 UTC
The button that opens the main nav submenu keeps adding the same expanded class on the submenu every time you press it

**Comment by kjellr** [comment] 2018-12-09 21:00
@anevins12 Can you share more specifics of this bug? In my testing, the classes seem to appear and disappear as expected: 

![menu-classes](https://user-images.githubusercontent.com/1202812/49702849-14be2400-fbc3-11e8-9fa6-6f61f42fc5e1.gif)

**Comment by anevins12** [comment] 2018-12-09 23:14
If you get rid of the fixed position on the submenu, you'll have the button that opens the menu still in view. This also happens for the chevron down submenu buttons. 

![716](https://user-images.githubusercontent.com/2318561/49704224-2970db00-fc08-11e8-80a7-7cfb49d06461.gif)

As you can imagine, getting rid of the fixed menu is a realistic situation.

**Comment by allancole** [comment] 2018-12-10 18:30
Hmmm. I’m having trouble following this one as well @anevins12.

> If you get rid of the fixed position on the submenu, you'll have the button that opens the menu still in view. This also happens for the chevron down submenu buttons.

In your screenshot, it seems the issue only happens when you manually change the sub-menu to `position: static;` in the console. If you don’t manually change that position, by default the menu is set to `position: fixed`, so I’m not sure I understand how this problem is caused by the theme. 

Could you clarify a bit more or maybe describe what you’re trying to do by changing the menu position?

**Comment by crunnells** [comment] 2019-01-12 00:55
This issue is hypothetical, since it would require someone changing the CSS properties in order to trigger the problem. It's also worth noting that I could only replicate this problem in Chrome. I think it's fair to close this issue.

**Closed by crunnells** 2019-01-12 00:55 UTC
Labels: bug, needs testing

**Comment by anevins12** [comment] 2019-01-12 01:19
@crunnells At least worth taking this as a learning point forward
